### ISSUE TITLE
Find `TODO: `

### ISSUE THREAD

**Issue by nikivdev** [aymericbeaumet/squeeze#2]
I'd love for it to extract `TODO: ` as well as an option. My use case is I want to bind a key to turn a line like:

`// TODO: check if cmd is installed` 

Into:

`// if cmd is installed`

In VSCode or some other editor.

Although on second thought, squeeze only does the finding part, I can just directly edit the string I get. Still it might be useful to find all `TODO: ` in the project/file perhaps easily.

**Comment by aymericbeaumet** [comment]
I guess the scope of squeeze would be to extract everything coming after `TODO:`:

```bash
echo 'foobar // TODO: check if cmd is installed' | squeeze --todo
# check if cmd is installed
```

Removing the `check` and inserting the comment would be up to your plugin.

**Comment by aymericbeaumet** [comment]
Implemented in https://github.com/aymericbeaumet/squeeze/pull/3 (you need the rust toolchain for the moment). I widened the scope to the concept of [codetags](https://www.python.org/dev/peps/pep-0350/).

- Search for all codetags:
```shell
$ echo 'foobar // FIXME: check if cmd is installed' | squeeze --codetag
FIXME: check if cmd is installed
```

- Limit to TODOs:

```shell
$ echo 'foobar // TODO: check if cmd is installed' | squeeze --codetag=todo
TODO: check if cmd is installed
```

- For convenience I also exposed the `--todo` alias:

```shell
$ echo 'foobar // TODO: check if cmd is installed' | squeeze --todo
TODO: check if cmd is installed
```

- Limit to TODOs, do not output the mnemonic:

```shell
$ echo 'foobar // TODO: check if cmd is installed' | squeeze --todo --hide-mnemonic
check if cmd is installed
```

**Comment by aymericbeaumet** [comment]
In your case you might also be interested into limiting to the first result `squeeze --first --todo --hide-mnemonic`

**Comment by nikivdev** [comment]
Thanks. Works great ❤️
